// Cuts the character artwork (references/personaje.png) into rig pieces and
// writes them, with transparency, to assets/personaje-sprites.js as data URIs
// (data URIs keep the page working from file:// without a tainted canvas).
//
//   node tools/cut_sprites.js
//
// Requires Playwright (uses the headless browser's canvas to do the cutting).
// All coordinates below are pixels in the 1672x941 source illustration.

const fs = require('fs');
const path = require('path');
let chromium;
try { ({ chromium } = require('playwright')); }
catch { ({ chromium } = require('/opt/node22/lib/node_modules/playwright')); }

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'references/personaje.png');
const OUT = path.join(ROOT, 'assets/personaje-sprites.js');

// Outline polygons traced around each piece. `key` removes the blue brush
// background that sits directly behind the legs in the illustration.
const PIECES = {
  // Head, torso, both arms and the shorts, cut along the shorts hem.
  upper: { key: false, poly: [
    [700, 40], [760, 5], [860, 5], [905, 70], [930, 85], [1000, 95], [1110, 120],
    [1150, 160], [1210, 185], [1290, 205], [1345, 212], [1385, 232], [1402, 275],
    [1388, 290], [1350, 272], [1300, 258], [1240, 248], [1170, 233], [1140, 222],
    [1070, 280], [1065, 320], [1085, 340], [1097, 400], [1097, 500], [1082, 528],
    [1040, 535], [990, 533], [960, 505], [950, 472], [935, 450], [905, 435],
    [870, 440], [846, 462], [830, 492], [808, 505], [798, 478], [812, 425],
    [835, 370], [855, 335], [820, 300], [760, 280], [700, 280], [620, 295],
    [560, 308], [500, 325], [472, 335], [452, 358], [428, 352], [424, 318],
    [440, 300], [470, 288], [520, 268], [600, 238], [655, 200], [690, 175],
    [700, 120], [690, 80],
  ] },
  // Front (right) thigh from under the shorts to just below the knee cap.
  thigh: { key: true, poly: [
    [818, 520], [820, 490], [832, 466], [850, 446], [885, 434], [925, 440],
    [950, 460], [953, 500], [937, 545], [918, 585], [914, 606], [900, 620],
    [866, 626], [832, 620], [818, 604], [826, 565],
  ] },
  // Sock: red/white turnover band and black stocking down to the boot.
  shin: { key: true, poly: [
    [812, 602], [914, 602], [912, 690], [897, 702], [891, 790], [834, 790],
    [826, 700], [816, 690],
  ] },
  // Laced high-top boot.
  boot: { key: true, poly: [
    [833, 768], [892, 768], [902, 800], [906, 850], [897, 873], [870, 877],
    [790, 874], [760, 870], [760, 850], [776, 834], [804, 812], [830, 792],
  ] },
  // Leather ball (circle).
  ball: { key: true, circle: [635, 800, 69] },
};

(async () => {
  const b = await chromium.launch();
  const p = await b.newPage();
  const data = 'data:image/png;base64,' + fs.readFileSync(SRC).toString('base64');
  const out = await p.evaluate(async ([data, PIECES]) => {
    const img = new Image(); img.src = data; await img.decode();
    const res = {};
    for (const [name, pc] of Object.entries(PIECES)) {
      let xs, ys;
      if (pc.circle) {
        const [cx, cy, r] = pc.circle;
        xs = [cx - r, cx + r]; ys = [cy - r, cy + r];
      } else { xs = pc.poly.map(q => q[0]); ys = pc.poly.map(q => q[1]); }
      const x0 = Math.floor(Math.min(...xs)) - 2, y0 = Math.floor(Math.min(...ys)) - 2;
      const w = Math.ceil(Math.max(...xs)) - x0 + 4, h = Math.ceil(Math.max(...ys)) - y0 + 4;
      const c = document.createElement('canvas'); c.width = w; c.height = h;
      const g = c.getContext('2d');
      g.beginPath();
      if (pc.circle) g.arc(pc.circle[0] - x0, pc.circle[1] - y0, pc.circle[2], 0, Math.PI * 2);
      else pc.poly.forEach(([x, y], i) => g[i ? 'lineTo' : 'moveTo'](x - x0, y - y0));
      g.closePath(); g.clip();
      g.drawImage(img, -x0, -y0);
      if (pc.key) {
        const id = g.getImageData(0, 0, w, h), d = id.data;
        for (let i = 0; i < d.length; i += 4) {
          const r = d[i], gg = d[i + 1], bb = d[i + 2];
          // bright/medium blue brush paint → transparent; soft edge
          const blueness = bb - Math.max(r, gg * 0.85);
          if (bb > 95 && blueness > 30) d[i + 3] = 0;
          else if (bb > 80 && blueness > 18) d[i + 3] = Math.min(d[i + 3], 110);
        }
        g.putImageData(id, 0, 0);
      }
      res[name] = { x: x0, y: y0, w, h, src: c.toDataURL('image/png') };
    }
    return res;
  }, [data, PIECES]);
  const js = '// Generated by tools/cut_sprites.js from references/personaje.png — do not edit.\n' +
    'window.PERSONAJE_SPRITES = ' + JSON.stringify(out) + ';\n';
  fs.writeFileSync(OUT, js);
  console.log('wrote', path.relative(ROOT, OUT), (js.length / 1024).toFixed(0) + ' KB',
    Object.entries(out).map(([k, v]) => `${k} ${v.w}x${v.h}@${v.x},${v.y}`).join(' | '));
  await b.close();
})();
